### ISSUE TITLE
Fixing one expression makes other suggestions disappear.

### ISSUE THREAD

**Issue by Thalos12** [sourcery-ai/sourcery-vscode#12]
I noticed that after manually applying one suggestion, the others disappear.

Consider for instance this function I wrote

```python
def f(a,b):
    c = dict()

    if (a is not None) and (b is not None):
        print("Working.")
```

Sourcery suggested to change line 2 to `c = {}` and line 4 to `if not (a is None or b is None):`, as shown below.

![Schermata del 2020-05-15 16-38-29-cut](https://user-images.githubusercontent.com/13919407/82062815-f5d29400-96ca-11ea-95d6-80baaefcf480.png)

I decided to change the first expression manually, but after saving the second suggestion disappeared even though I had not changed it.
Writing again `c = dict()` made both suggestions reappear.

Changing the second expression manually did not make the first one disappear.

Using `Ctrl+.` on the first expression and clicking on `Simplify logical expression, Replace dict() with {}` did not make the second disappear. However, until the first expression was not simplified by sourcery, there was no way to fix the second one, and using `Ctrl+.` on it showed just the fix for the first one.

**Comment by Hellebore** [comment]
Thanks for raising - am able to reproduce.
Will investigate!

**Comment by Hellebore** [comment]
Fix identified - should be in our next release.

**Comment by Hellebore** [comment]
Fixed with release 0.2.5 of vscode extension.

**Comment by Thalos12** [comment]
I updated the extension and it works as expected.
Thank you!

**Comment by Thalos12** [comment]
Actually, something still does not seem right, please look at the gif below

![output](https://user-images.githubusercontent.com/13919407/83949275-118d0e00-a823-11ea-8cc6-9310290fa270.gif)

There are two issues that I can see:
- multiple refactors are shown together when the cursor is standing still
- just the refactor relevant for the line under the cursor is shown while the mouse is moving along the line

I did not create another issue because this seems related to what was happening before.

**Comment by brendanator** [comment]
What's happening here is that VSCode is only showing the diff when the mouse cursor has stopped moving. When it is moving it is only showing the description of the changes that Sourcery is going to make. If you scroll down in the diff you will see the same description. In both cases there's 2 refactorings being shown:
- Replace dict() with {}
- Simplify logical expression

At the moment Sourcery suggests all refactorings it finds in a function at the same time, it doesn't split them apart. We will think about how we can do this in the future

**Comment by Thalos12** [comment]
Thank you for the explanation!
