### ISSUE TITLE
recent update breaks sourcery extensions

### ISSUE THREAD

**Issue by ngam** [sourcery-ai/sourcery-vscode#52]
hi again, I think your latest update breaks the extension on a regular linux64 machine with the following error:

```bash
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ~/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/cryptography/hazmat/bindings/_rust.so)
```

**Comment by Hellebore** [comment]
Hi - thanks for the report - which linux version do you have?

**Comment by ngam** [comment]
```bash
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Workstation"
VARIANT_ID="workstation"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:workstation"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
```

```bash
$ uname -i
x86_64
```

```
$ uname -o
GNU/Linux
```

From working with the conda-forge crowd, `GLIBC_2.18` is basically pretty new stuff, so this update will likely be breaking sourcery on a lot of older machines (or machines with LTS OS that's not been upgraded to the latest stuff).

**Comment by ngam** [comment]
(This is not my "personal" machine --- it is a "work" machine where I don't have proper sudo rights to upgrade, so...)

**Comment by mxsmns** [comment]
I'm running into the same issue with v0.9.7 of the extension on a very similar RHEL7 setup. Downgrading the extension to v0.9.5 seems to get it working again locally.

**Comment by russhughes** [comment]
I'm seeing the same error as well on CentOS Linux release 7.9.2009 (Core).

**Comment by AlexHarn** [comment]
Same for me, on all my remove dev nodes I use via SSH.

**Comment by brendanator** [comment]
We recently updated the version of cryptography that Sourcery uses. Cryptography now include rust bindings which created this issue. 

The next version of Sourcery will fix this issue by including a manylinux2010 compiled version of cryptography

**Comment by ngam** [comment]
@brendanator, thanks! 

This has been happening with a few times in OS-related things (e.g. your extension breaks as well when it's an arm-based processor). Could you please have a look and clean up the deps to ensure the extension works across different OSs if possible? Or if you tell us which deps is holding you back, we can chase them for you :)

**Comment by ngam** [comment]
As in, something like cryptography may the same source of arm64 issues... most things have supported the new arch, so it could well be simply changing versions, etc. like with the manylinux2010 fix above.

**Comment by Hellebore** [comment]
@ngam this should now be fixed with our latest update - 0.9.8. Could you try it out and let us know?

**Comment by ngam** [comment]
@Hellebore thanks for following up, it looks like the issue with glibc is resolved. The arm64/aarch64 issues persist (in particular, sourcery on arm64 still runs through rosetta and it completely fails on aarch64, indicating a complete lack of support for arm)

**Comment by Hellebore** [comment]
@ngam thanks - I will close this and we will keep that one for broader ARM support. Probably the main thing we need to do is set up a build environment in GitHub actions that runs on ARM - currently we only build for windows, linux and mac, all on intel.
