### ISSUE TITLE
Fails To start on WSL Alpine

### ISSUE THREAD

**Issue by DrMagPie** [sourcery-ai/sourcery-vscode#53]
Hello when Sourcery starts it throws out this error:
```
Traceback (most recent call last):
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/__main__.py", line 8, in <module>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/binary/command_line_interface.py", line 14, in <module binary.command_line_interface>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/binary/auth.py", line 11, in <module binary.auth>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/binary/env.py", line 3, in <module binary.env>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/binary/sentry.py", line 9, in <module binary.sentry>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/lib/auth/client_auth.py", line 3, in <module lib.auth.client_auth>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/jwt/__init__.py", line 1, in <module jwt>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/jwt/api_jwk.py", line 3, in <module jwt.api_jwk>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/jwt/algorithms.py", line 6, in <module jwt.algorithms>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/jwt/utils.py", line 6, in <module jwt.utils>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/cryptography/hazmat/primitives/asymmetric/ec.py", line 13, in <module cryptography.hazmat.primitives.asymmetric.ec>
  File "/home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/cryptography/hazmat/primitives/asymmetric/utils.py", line 6, in <module cryptography.hazmat.primitives.asymmetric.utils>
ImportError: Error relocating /home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/libgcc_s.so.1: __cpu_indicator_init: symbol not found
[Error - 3:16:02 PM] Connection to server got closed. Server will not be restarted.
```

this is a brand new install

**Comment by Hellebore** [comment]
Thanks for reporting! - We should be fixing this in our next release in a few days - it was an issue with our linux build environment.

**Comment by brendanator** [comment]
Actually I doubt this will work in Alpine. The Sourcery Linux binary is built with `glibc` and we don't currently build or publish a version that is built using `musl`

**Comment by DrMagPie** [comment]
Happy to hear that it will be fixed for Linux in general.

Sad that you didn't have have a dedicated release for 'musl'.
But that shouldn't be a problem there are dirty hacks to make it work. And 'glibc' compatibility thingy for 'musl' also should work

**Comment by Hellebore** [comment]
@DrMagPie we've now released our fix for the glibc issue in 0.9.8 - could you try it out?

**Comment by DrMagPie** [comment]
Thank you for letting me know.
I will test it next Monday.

**Comment by DrMagPie** [comment]
Hi,

I have tried it right now. The problem still persists. So or the Linux thingy was not fixed. or [gcompat](https://git.adelielinux.org/adelie/gcompat) is not working to translate it from `glibc` to `musl`.

I will try to find sometime later today or tomorrow to test it with `Ubuntu` or `Debian`

**Comment by LeGmask** [comment]
I have the same issue, any news ?

**Comment by Hellebore** [comment]
@LeGmask Since we build with glibc we are not supporting Alpine currently. Will update this issue if that changes in future.

**Comment by LeGmask** [comment]
> @LeGmask Since we build with glibc we are not supporting Alpine currently. Will update this issue if that changes in future.

Well yes but I have the same issue on arch Linux ....

**Comment by Hellebore** [comment]
@LeGmask could you try the Arch linux libxcrypt workaround here?
https://docs.sourcery.ai/Troubleshooting/

**Comment by LeGmask** [comment]
> @LeGmask could you try the Arch linux libxcrypt workaround here? [docs.sourcery.ai/Troubleshooting](https://docs.sourcery.ai/Troubleshooting/)

Okay that's works perfectly :stuck_out_tongue: niiiice !
But since all these day it was just in the [Troubleshooting](https://docs.sourcery.ai/Troubleshooting/) section ?
